import React from "react";
import {
  Box,
  VStack,
  useColorMode,
  Flex,
  Text,
  Accordion,
} from "@chakra-ui/react";
import { darkColor, lightColor } from "../../colors";
import { useSelector } from "react-redux";
import FaqItem from "./FaqItem";
import { convertNanosecondsToDays } from "../../tools/conversions";

const RewardsFaq = () => {
  const { colorMode, toggleColorMode } = useColorMode();
  const { protocol_fee_percentage, reward_timer_duration_nanos } = useSelector(
    (state) => state.Protocol
  );

  const faqs = [
    {
      title: "What are rewards?",
      body: `Rewards are new ICP tokens earned from staking. The reward pool automatically increases every few days as these staking rewards accumulate. These accumulated rewards are then disbursed to one lucky winner every ${convertNanosecondsToDays(
        Number(reward_timer_duration_nanos)
      )} days.`,
    },
    {
      title: "Where do the rewards come from?",
      body: "The NeuronPool smart contract controls a neuron on the Network Nervous System (NNS). This neuron votes on governance proposals and earns ICP rewards for doing so. The ICP rewards come from the NNS / the ICP network.",
    },
    {
      title: "How do I collect a reward?",
      body: "If you have been lucky and won a reward, it will be visible in the 'Collect' section. After the 7-day unlock duration has passed, your reward will be ready to collect.",
    },
    {
      title: "How are winners picked?",
      body: `The NeuronPool smart contract uses a weighted selection algorithm with a random number that is generated by the ICP blockchain to select a winner. Your chances of winning are proportional to the amount you have staked. The higher your stake relative to the total stake, the higher your odds of winning.`,
    },
    {
      title: "When are winners picked?",
      body: `One winner is picked every ${convertNanosecondsToDays(
        Number(reward_timer_duration_nanos)
      )} days. This duration may be adjusted in the future based on user preferences and usage.`,
    },
    {
      title: "Is there a fee on rewards?",
      body: `Currently, there is a ${protocol_fee_percentage}% fee on rewards, which is paid to the NeuronPool smart contract.`,
    },
  ];

  return (
    <Box>
      <Flex mt={6}>
        <Text
          fontWeight="bold"
          color={colorMode === "light" ? darkColor : lightColor}
        >
          Rewards FAQ
        </Text>
      </Flex>
      <Accordion defaultIndex={[0]} mt={3} w="100%" allowMultiple reduceMotion>
        <VStack gap={3}>
          {faqs.map(({ title, body }) => (
            <FaqItem key={title} title={title} body={body} />
          ))}
        </VStack>
      </Accordion>
    </Box>
  );
};

export default RewardsFaq;
